name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: |
        cd $GITHUB_WORKSPACE
        yarn install

    - name: Build
      run: yarn build

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
